spring.application.name=demo

# Conexi\u00f3n a PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.qkekmzgmazoqczgnpuvx
spring.datasource.password=IHj3PGWpjeiJMABL

# Configuraci\u00f3n de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true