spring.application.name=demo

# Configuraci\u00f3n del puerto para Railway
server.port=${PORT:8080}

# Conexi\u00f3n a PostgreSQL usando variables de entorno
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Configuraci\u00f3n de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true