spring.application.name=demo
server.port=${PORT:8080}

# Pega aqu\u00ed la URL de conexi\u00f3n de Railway anteponi\u00e9ndole "jdbc:"
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:YxckHcJuisGhMaQemcpVWCWytKhfFNWH@postgres.railway.internal:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YxckHcJuisGhMaQemcpVWCWytKhfFNWH}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver